repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0 # Use the latest stable version
    hooks:
      - id: cargo-check
      - id: fmt
      - id: clippy
  - repo: local
    hooks:
      - id: cargo-doc-check
        name: cargo-doc-check
        entry: zsh -c "RUSTDOCFLAGS='-D warnings' cargo doc --no-deps --document-private-items"
        language: system
        pass_filenames: false
