# Docker Compose file for just PostGres and migrations,
# so we can debug code locally without running the full app through Docker Compose
services:
  # Main PostgreSQL service
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: prodcast
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # sqlx CLI service using local image
  sqlx:
    build:
      context: ..
      dockerfile: ./docker/sqlx.Dockerfile
    container_name: sqlx    
    working_dir: /app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://prodcast:password@postgres/newsletter
    command: ["migrate", "run"]
    restart: "no"

volumes:
  postgres_data:
    driver: local
